# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\merna\Merna\Programming\Python\MRI\MRI 1\fourier.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 473)
        MainWindow.setMinimumSize(QtCore.QSize(400, 473))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 8, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 6, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        self.btnToggle = QtWidgets.QPushButton(self.centralwidget)
        self.btnToggle.setObjectName("btnToggle")
        self.gridLayout.addWidget(self.btnToggle, 7, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbImg = QtWidgets.QLabel(self.centralwidget)
        self.lbImg.setMinimumSize(QtCore.QSize(128, 128))
        self.lbImg.setFrameShape(QtWidgets.QFrame.Box)
        self.lbImg.setText("")
        self.lbImg.setObjectName("lbImg")
        self.horizontalLayout.addWidget(self.lbImg)
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart, 0, QtCore.Qt.AlignVCenter)
        self.lbFFTimg = QtWidgets.QLabel(self.centralwidget)
        self.lbFFTimg.setMinimumSize(QtCore.QSize(128, 128))
        self.lbFFTimg.setFrameShape(QtWidgets.QFrame.Box)
        self.lbFFTimg.setText("")
        self.lbFFTimg.setObjectName("lbFFTimg")
        self.horizontalLayout.addWidget(self.lbFFTimg)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setMinimumSize(QtCore.QSize(100, 0))
        self.btnBrowse.setObjectName("btnBrowse")
        self.verticalLayout.addWidget(self.btnBrowse, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbnline = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbnline.sizePolicy().hasHeightForWidth())
        self.lbnline.setSizePolicy(sizePolicy)
        self.lbnline.setScaledContents(False)
        self.lbnline.setWordWrap(True)
        self.lbnline.setObjectName("lbnline")
        self.horizontalLayout_3.addWidget(self.lbnline, 0, QtCore.Qt.AlignHCenter)
        self.nLines = QtWidgets.QSpinBox(self.centralwidget)
        self.nLines.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.nLines.setMinimum(1)
        self.nLines.setMaximum(64)
        self.nLines.setObjectName("nLines")
        self.horizontalLayout_3.addWidget(self.nLines)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.lbFixedImg = QtWidgets.QLabel(self.centralwidget)
        self.lbFixedImg.setMinimumSize(QtCore.QSize(128, 128))
        self.lbFixedImg.setMaximumSize(QtCore.QSize(800, 800))
        self.lbFixedImg.setFrameShape(QtWidgets.QFrame.Box)
        self.lbFixedImg.setText("")
        self.lbFixedImg.setObjectName("lbFixedImg")
        self.horizontalLayout_2.addWidget(self.lbFixedImg)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 15))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 5, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 3, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 18))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBrowse = QtWidgets.QAction(MainWindow)
        self.actionBrowse.setObjectName("actionBrowse")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuMenu.addAction(self.actionBrowse)
        self.menuMenu.addAction(self.actionClose)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fourier"))
        self.btnToggle.setText(_translate("MainWindow", "PushButton"))
        self.btnStart.setText(_translate("MainWindow", "Start Transform"))
        self.btnBrowse.setText(_translate("MainWindow", "Browse"))
        self.lbnline.setText(_translate("MainWindow", "Enter number of lines"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionBrowse.setText(_translate("MainWindow", "Browse"))
        self.actionClose.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

